"""initial migration with isolated states

Revision ID: f9e5697989a3
Revises: 
Create Date: 2026-06-02 00:41:00.095372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e5697989a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemas',
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('cinema_name', sa.String(length=150), nullable=False),
    sa.Column('cinema_address', sa.String(length=200), nullable=False),
    sa.Column('cinema_location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cinema_id')
    )
    op.create_table('movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(length=300), nullable=False),
    sa.Column('movie_duration', sa.Integer(), nullable=False),
    sa.Column('movie_description', sa.String(length=10000), nullable=False),
    sa.Column('movie_rating', sa.Float(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('languages', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('poster_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('movie_id'),
    sa.UniqueConstraint('movie_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cnic', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('cnic'),
    sa.UniqueConstraint('email')
    )
    op.create_table('screens',
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(length=150), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.cinema_id'], ),
    sa.PrimaryKeyConstraint('screen_id')
    )
    op.create_table('seats',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.String(length=10), nullable=False),
    sa.CheckConstraint('seat_number > 0 AND seat_number < 100', name='check_seat_number_range'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.screen_id'], ),
    sa.PrimaryKeyConstraint('seat_id'),
    sa.UniqueConstraint('screen_id', 'seat_number', name='uq_screen_seat_number')
    )
    op.create_table('shows',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('show_date', sa.Date(), nullable=False),
    sa.Column('show_time', sa.Time(), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.screen_id'], ),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('booking_status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='bookingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('show_seats',
    sa.Column('show_seats_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('BOOKED', 'LOCKED', 'AVAILABLE', name='seatstatus'), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.seat_id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ),
    sa.PrimaryKeyConstraint('show_seats_id'),
    sa.UniqueConstraint('show_id', 'seat_id', name='uq_show_seat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_seats')
    op.drop_table('bookings')
    op.drop_table('shows')
    op.drop_table('seats')
    op.drop_table('screens')
    op.drop_table('users')
    op.drop_table('movies')
    op.drop_table('cinemas')
    # ### end Alembic commands ###
